### ISSUE TITLE
XLNet model params for Question answering 

### ISSUE THREAD

**Issue by Swathygsb** [huggingface/transformers#1852]
Model: XLNet for QA
model(parameters ...)
RuntimeError: CUDA error: device-side assert triggered

**Comment by Swathygsb** [comment]
What parameters should I exactly pass for XLNet QA model?

**Comment by iedmrc** [comment]
More details would be nice but please check #1849 #1848 and #1805 . Also set `CUDA_LAUNCH_BLOCKING=1` environment variable to have more details about the error, from the CUDA.

**Comment by Swathygsb** [comment]
Thanks. It worked after changing the input sequence limit to 128.
