### ISSUE TITLE
AutoModelForCausalLM.from_pretrained is killed by Loading checkpoint shards:

### ISSUE THREAD

**Issue by 50516017** [huggingface/transformers#26283]
### System Info

`- `transformers` version: 4.34.0.dev0
- Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>`

### Who can help?

@younesbelkada,@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I would like to fine tune AIBunCho/japanese-novel-gpt-j-6b using QLora. When I executed AutoModelForCausalLM.from_pretrained, it was killed by the python function and execution stopped. I was looking at the task manager and found that it was caused by CPU usage, but is it possible to load pretrained on the GPU? I have been able to fine tune other smaller models with Lora without any problems.
code is 
````
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
model_name = "AIBunCho/japanese-novel-gpt-j-6b"
config = AutoConfig.from_pretrained(model_name,use_fast=False)
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16
    )
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=config,
    device_map="cuda",
    load_in_8bit=True,
    #quantization_config=bnb_config
    
)
`

### Expected behavior

```
 Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA exception! Error code: no CUDA-capable device is detected
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/shimizu/create_LLM/macin/work2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/shimizu/create_LLM/macin/work2/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
None
Loading checkpoint shards:   0%|                                                                  | 0/2 [00:00<?, ?it/s]Killed
```

**Comment by jmanhype** [comment]
Having similar lssue

**Comment by younesbelkada** [comment]
Hi @50516017 @jmanhype 
This is because the first shard of the model is ~10GB, what I usually do is to push a smaller sharded version on the Hub.
I have just pushed a version with smaller shards under: `ybelkada/japanese-novel-gpt-j-6b-sharded`: https://huggingface.co/ybelkada/japanese-novel-gpt-j-6b-sharded - can you try that out instead?
In the future, to create these repos you can run:

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id = "AIBunCho/japanese-novel-gpt-j-6b"
target_model_id = "yourusername/japanese-novel-gpt-j-6b-sharded"

model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.bfloat16, low_cpu_mem_usage=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)

model.push_to_hub(target_model_id, max_shard_size="2GB")
tokenizer.push_to_hub(target_model_id)
```

**Comment by jxmorris12** [comment]
When this happened to me, I could fix it by just adding the arguments to load in half precision (`torch_dtype=torch.bfloat16`) and to initialize without duplicating the parameters in memory (`low_cpu_mem_usage=True`).

**Comment by gautam-17-2003** [comment]
`# The model that you want to train from the Hugging Face hub
model_name = "mistralai/Mixtral-8x7B-Instruct-v0.1"

# The instruction dataset to use
dataset_name = "vwxyzjn/openhermes-dev__mistralai_Mixtral-8x7B-Instruct-v0.1__1706886961"

# Fine-tuned model name
new_model = "Mixtral-8x7B-Instruct-finetune"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map=device_map
)`
i am using this mixtral instruct model and i am getting a KeyError: 'mixtral'

**Comment by younesbelkada** [comment]
@gautam-17-2003 can you try `pip install -U transformers`

**Comment by gautam-17-2003** [comment]
@younesbelkada I've already tried this but this is still not working for me

**Comment by gautam-17-2003** [comment]
```
# The model that you want to train from the Hugging Face hub
model_name = "mistralai/Mixtral-8x7B-Instruct-v0.1"

# The instruction dataset to use
dataset_name = "vwxyzjn/openhermes-dev__mistralai_Mixtral-8x7B-Instruct-v0.1__1706886961"

# Fine-tuned model name
new_model = "Mixtral-8x7B-Instruct-finetune"

################################################################################
# QLoRA parameters
################################################################################

# LoRA attention dimension
lora_r = 64

# Alpha parameter for LoRA scaling
lora_alpha = 16

# Dropout probability for LoRA layers
lora_dropout = 0.1

################################################################################
# bitsandbytes parameters
################################################################################

# Activate 4-bit precision base model loading
use_4bit = True

# Compute dtype for 4-bit base models
bnb_4bit_compute_dtype = "float16"

# Quantization type (fp4 or nf4)
bnb_4bit_quant_type = "nf4"

# Activate nested quantization for 4-bit base models (double quantization)
use_nested_quant = False

################################################################################
# TrainingArguments parameters
################################################################################

# Output directory where the model predictions and checkpoints will be stored
output_dir = "./results"

# Number of training epochs
num_train_epochs = 1

# Enable fp16/bf16 training (set bf16 to True with an A100)
fp16 = False
bf16 = False

# Batch size per GPU for training
per_device_train_batch_size = 4

# Batch size per GPU for evaluation
per_device_eval_batch_size = 4

# Number of update steps to accumulate the gradients for
gradient_accumulation_steps = 1

# Enable gradient checkpointing
gradient_checkpointing = True

# Maximum gradient normal (gradient clipping)
max_grad_norm = 0.3

# Initial learning rate (AdamW optimizer)
learning_rate = 2e-4

# Weight decay to apply to all layers except bias/LayerNorm weights
weight_decay = 0.001

# Optimizer to use
optim = "paged_adamw_32bit"

# Learning rate schedule
lr_scheduler_type = "cosine"

# Number of training steps (overrides num_train_epochs)
max_steps = -1

# Ratio of steps for a linear warmup (from 0 to learning rate)
warmup_ratio = 0.03

# Group sequences into batches with same length
# Saves memory and speeds up training considerably
group_by_length = True

# Save checkpoint every X updates steps
save_steps = 0

# Log every X updates steps
logging_steps = 25

################################################################################
# SFT parameters
################################################################################

# Maximum sequence length to use
max_seq_length = None

# Pack multiple short examples in the same input sequence to increase efficiency
packing = False

# Load the entire model on the GPU 0
device_map = {"": 0}

# Load dataset (you can process it here)
dataset = load_dataset(dataset_name, split='train_prefs')

# Load tokenizer and model with QLoRA configuration
compute_dtype = getattr(torch, bnb_4bit_compute_dtype)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=use_4bit,
    bnb_4bit_quant_type=bnb_4bit_quant_type,
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=use_nested_quant,
)

# Check GPU compatibility with bfloat16
if compute_dtype == torch.float16 and use_4bit:
    major, _ = torch.cuda.get_device_capability()
    if major >= 8:
        print("=" * 80)
        print("Your GPU supports bfloat16: accelerate training with bf16=True")
        print("=" * 80)


# Load base model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map=device_map
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# Load LLaMA tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right" # Fix weird overflow issue with fp16 training

# Load LoRA configuration
peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM",
)

# Set training parameters
training_arguments = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=num_train_epochs,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="tensorboard"
)

# Set supervised fine-tuning parameters
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=packing,
)

# Train model
trainer.train()
```
here's the code for your reference @younesbelkada

**Comment by gautam-17-2003** [comment]
@younesbelkada thanks it's working now

**Comment by ArthurZucker** [comment]
🤗

**Comment by zhuodicai** [comment]
It's true. Set `torch_dtype=torch.bfloat16` and `low_cpu_mem_usage=True` together.

**Comment by DrewGalbraith** [comment]
PyTorch has this function to load for inference only (which is my goal):
```python
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH, weights_only=True))
```
But I can't find anything in a HF documentation that supports this. Am I missing something?

**Comment by ArthurZucker** [comment]
Few things, 1. the dtype you are using by default is gonna be `float32` 2. transformers does not load gradients either so this should not be the problem!
