### ISSUE TITLE
`load_in_4bit=True` works only with models in `safetensors` format

### ISSUE THREAD

**Issue by danielkorat** [huggingface/transformers#27708]
### System Info

Hi,

When testing on `Google Colab (Free Tier T4 GPU)`, this code crashes with RAM OOM [(Notebook)](https://colab.research.google.com/drive/1zAzdcH_KRQuc_0zWBEzYuaV1h4ERgzPy?usp=sharing):

```python
AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1", load_in_4bit=True, device_map="auto")
```

![image](https://github.com/huggingface/transformers/assets/32893314/11f62cdc-b94c-4e68-9783-c4d25904f194)

However, when loading the safetensors revision, it works:

```python
AutoModelForCausalLM.from_pretrained("mistralai/Mistral-7B-v0.1", load_in_4bit=True, device_map="auto", revision="/refs/pr/91")
```

```bash
transformers==4.35.2
accelerate==0.24.1
bitsandbytes==0.41.2.post2
```

cc @ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Colab link that reproduces the problem: [Notebook](https://colab.research.google.com/drive/1zAzdcH_KRQuc_0zWBEzYuaV1h4ERgzPy?usp=sharing)

### Expected behavior

Successful loading of the model onto GPU.

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting. Regarding the accelerate dispatching, I am not too sure why this happens, so I'll ping @SunMarc to see if this is expected, but I would not be surprised that `safetensors` supports loading each parameters indivudally, casting them and then saving. 
Also I think that using smaller shards is usually what we do in this case, feel free to use: https://huggingface.co/ybelkada/Mistral-7B-v0.1-bf16-sharded

**Comment by danielkorat** [comment]
Thanks @ArthurZucker 
Since this is a very general use cases, and also happens out of the blue for many existing models like `Intel/neural-chat-7b-v1-1` as well, I think there should be some fix or at least a warning. Thanks

**Comment by younesbelkada** [comment]
Hi @danielkorat 
As @ArthurZucker stated we changed the default max shard size to support google colab inference easily, for previous models, unfortunately one needs to manually shard the model and push it on the hub under a new model id.

**Comment by danielkorat** [comment]
I see.
I solved it in my case by merging the safetensors PR, under the same model_id (`Intel/neural-chat-v3-1`). 
I think users like me and others I've seen might be running into this issue right now in Colab, without any explanation of the cause. Would be nice if there was at least a warning when loading very large shards.
@younesbelkada

**Comment by younesbelkada** [comment]
Hi @danielkorat 
Thanks! 
Hmmm I think this might introduce a lot of verbosity in transformers as this would only be relevant in the case people use google colab

**Comment by danielkorat** [comment]
Then you can probably close this, thanks.

**Comment by younesbelkada** [comment]
Thank you @danielkorat !
