### ISSUE TITLE
Implementation of SDPA for Microsoft Phi-3 Mini

### ISSUE THREAD

**Issue by Dev4011** [huggingface/transformers#31863]
### System Info

- `transformers` version: 4.42.3
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using distributed or parallel set-up in script?: Yes
- Using GPU in script?: Yes
- GPU type: Tesla T4

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am referring to the below tutorial to finetune Microsoft Phi3 on my custom dataset: https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-lora-python.ipynb

As I am doing it on Colab on T4 GPU, the Flash Attention is not supported yet [FlashAttention only supports Ampere GPUs or newer.]

Thus, according to the below code from tutorial, attention_implementation is selected as 'sdpa' with compute datatype as torch.float16

if torch.cuda.is_bf16_supported():
  compute_dtype = torch.bfloat16
  attn_implementation = 'flash_attention_2'
else:
  compute_dtype = torch.float16
  attn_implementation = 'sdpa'

# Loading Model
model = AutoModelForCausalLM.from_pretrained(
    model_id, torch_dtype=compute_dtype, trust_remote_code=True, device_map='auto',
    attn_implementation=attn_implementation
)

# Error
It gives me the error: ValueError: Phi3ForCausalLM does not support an attention implementation through torch.nn.functional.scaled_dot_product_attention yet. Please request the support for this architecture: https://github.com/huggingface/transformers/issues/28005.

and keeping attention_implementation='eager' leads to CUDA Out of Memory error.

### Expected behavior

SDPA should be supported as an Attention Implementation for Microsoft Phi3 model

**Comment by ArthurZucker** [comment]
One thing to not is that `Phi3` uses `trust_remote_code=True`, meaning not sure it's compatible with transformers. 
AFAIK it is, se removing the `trust_remote_code=True`, should work

**Comment by pocca2048** [comment]
I think this can be changed to `True`?
https://github.com/huggingface/transformers/blob/3d7c2f9dea45338b7ebcd459b452e2fad7abfa1f/src/transformers/models/phi3/modeling_phi3.py#L844
I confirmed that model can be loaded properly after changing that to `True`.

**Comment by ArthurZucker** [comment]
Yep, can you open a PR? 🤗

**Comment by pocca2048** [comment]
@ArthurZucker Opened a PR!

**Comment by bjzhb666** [comment]
Hi, I changed the _supports_sdpa to True, but I still get this error. 

I am using V100. transformers version 4.42.4. How should I change the code? Thanks

**Comment by bjzhb666** [comment]
Oh, I set the trust_remote_code=False and set the _supports_sdpa to True. It works now.

**Comment by ArthurZucker** [comment]
Thanks for updating!
