### ISSUE TITLE
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [267,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by JHW5981** [huggingface/transformers#33985]
### System Info

- `transformers` version: 4.44.0
- Platform: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
- Python version: 3.12.0
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.31.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: yes, trainer helps me handle this.
- Using GPU in script?: yes, single gpu works ok, but multi-gpu cause problem
- GPU type: NVIDIA GeForce RTX 4090

### Who can help?

@muellerzr @SunMarc

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. I use chatgpt to generate a test training code on my environment setting, the code shows below:
```
from transformers import BertForSequenceClassification, BertTokenizer, Trainer, TrainingArguments
from datasets import Dataset

model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=2)
model.resize_token_embeddings(len(tokenizer))

data = {
    "text": ["This is a positive example", "This is a negative example"] * 50,
    "label": [1, 0] * 50  
}

dataset = Dataset.from_dict(data)

def preprocess_function(examples):
    return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=64)

encoded_dataset = dataset.map(preprocess_function, batched=True)


training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,  
    num_train_epochs=1,  
    logging_dir="./logs",
    logging_steps=10,
    evaluation_strategy="no"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset,
)

trainer.train()

print("Training completed.")
```
2. When I use only one gpu, that's:
```
CUDA_VISIBLE_DEVICES=5 NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" python test.py
```
Everything is ok.

3. When I use multi-gpu, that's:
```
CUDA_VISIBLE_DEVICES=5,6 NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" python test.py
```
Error comes:
/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
...
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 5947.60 examples/s]
/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|                                                                                                                                                                                            | 0/7 [00:00<?, ?it/s]/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
 14%|█████████████████████████▋                                                                                                                                                          | 1/7 [00:03<00:22,  3.74s/it]../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [126,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [126,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
......
../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [159,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/home/jihuawei2/projects/AceRead/model/test.py", line 47, in <module>
    trainer.train()
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 1948, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 2289, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 3328, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 3373, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1695, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1107, in forward
    extended_attention_mask = _prepare_4d_attention_mask_for_sdpa(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/modeling_attn_mask_utils.py", line 449, in _prepare_4d_attention_mask_for_sdpa
    if not is_tracing and torch.all(mask == 1):
                          ^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

 14%|█▍        | 1/7 [00:04<00:26,  4.38s/it]    

### Expected behavior

I believe this error is related to the package for parallel computation in Huggingface Trainer. I hope that eventually, I can achieve multi-card training on the 4090.

**Comment by ArthurZucker** [comment]
Hey! Would recommend you to run on CPU first, will tell you where this issue comes from! 🤗 Leaving the community to help as well

**Comment by JHW5981** [comment]
@ArthurZucker Thank you for your reply. The code runs without any issues on the CPU, and there are no problems with parallel training on four 3090s or four 2080s, nor with training on a single 4090. However, as soon as I use the trainer and set CUDA_VISIBLE_DEVICES to multiple GPUs, the issue arises.

**Comment by ArthurZucker** [comment]
Okay, in that case let me ping @muellerzr and @SunMarc for this! 🤗

**Comment by SunMarc** [comment]
Hi @JHW5981, thanks for the report ! Could you check if running 
`NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" python test.py` works ? It should use all the gpu available. 
If your issue only exist with 4090, I suggest you updating your driver !

**Comment by JHW5981** [comment]
@SunMarc Thanks for your reply. I check `NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" python test.py`, and found it did not work as well. Below is the error information:
```
Traceback (most recent call last):
  File "/home/jihuawei2/projects/AceRead/dustbin/test.py", line 42, in <module>
    main()
  File "/home/jihuawei2/projects/AceRead/dustbin/test.py", line 37, in main
    trainer.train()
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 1948, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 2289, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 3328, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/trainer.py", line 3373, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1695, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1141, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 694, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 584, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 514, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 394, in forward
    query_layer = self.transpose_for_scores(self.query(hidden_states))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jihuawei2/miniconda3/envs/main/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

  0%|          | 0/2 [00:16<?, ?it/s]  
```
I do think it is not the problem related to the 4090 device, because when i use 🤗accelarate to launch multi-gpus it works. So I think the problem maybe caused by some uncompatible behavior  of accelerate in Trainer? The example code shows below:
```
from accelerate import Accelerator
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from torch.utils.data import DataLoader, Dataset
import torch

class SimpleDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        return self.texts[idx], self.labels[idx]

texts = ["Hello, world!", "Hugging Face is great!"]
labels = [0, 1]
dataset = SimpleDataset(texts, labels)
dataloader = DataLoader(dataset, batch_size=2)

accelerator = Accelerator()
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model, dataloader = accelerator.prepare(model, dataloader)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)

for epoch in range(3):
    for batch in dataloader:
        optimizer.zero_grad()
        inputs = tokenizer(batch[0], padding=True, truncation=True, return_tensors="pt")
        outputs = model(**inputs, labels=batch[1])
        loss = outputs.loss
        accelerator.backward(loss)
        optimizer.step()
    print(f"Epoch {epoch + 1} completed.")

```
I use `accelerate launch  test.py`, and it works successfully(I just use twi gpu_ids here, because the other cards are used by other people):
```
Epoch 1 completed.
Epoch 1 completed.
Epoch 2 completed.
Epoch 2 completed.
Epoch 3 completed.
Epoch 3 completed.
```

**Comment by SunMarc** [comment]
Maybe the issue is with dataparallel ? Try to use DDP with accelerate instead by calling accelerate launch myscript.py --multi-gpu. More docs here: https://huggingface.co/docs/accelerate/en/basic_tutorials/launch#:~:text=You%20can%20also,mixed%20precision%20disabled%3A

**Comment by CurtainRight** [comment]
I also encountered the same mistake.
edition: trandformers== 4.48.1
Very strange. There were no errors when training the classification, but there were errors when training the summary model.

[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
[36m(RayTrainWorker pid=112196)[0m /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1422: indexSelectLargeIndex: block: [15,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
2025-02-25 19:19:17,316 ERROR tune_controller.py:1331 -- Trial task failed for trial TorchTrainer_5b17e_00000
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2772, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 919, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::_Inner.train()[39m (pid=112094, ip=172.16.52.65, actor_id=56b553fc9222478c438595540b000000, repr=TorchTrainer)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 57, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(RuntimeError): [36mray::_RayTrainWorker__execute.get_next()[39m (pid=112196, ip=172.16.52.65, actor_id=c74a1cfb304266a7736284e40b000000, repr=<ray.train._internal.worker_group.RayTrainWorker object at 0x7f1b289edc10>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/worker_group.py", line 33, in __execute
    raise skipped from exception_cause(skipped)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/_internal/utils.py", line 176, in discard_return_wrapper
    train_func(*args, **kwargs)
  File "/tmp/ray/session_2025-02-20_23-45-01_425090_27/runtime_resources/working_dir_files/s3_ray-fs_serve_jobs-591c09781fb9a044ae2a486d937e45fc/hf_text_summarization_trainer.py", line 116, in train_func
    trainTotal(dataset_df, tokenizer, config, corpus_df)
  File "/tmp/ray/session_2025-02-20_23-45-01_425090_27/runtime_resources/working_dir_files/s3_ray-fs_serve_jobs-591c09781fb9a044ae2a486d937e45fc/hf_text_summarization_trainer.py", line 360, in trainTotal
    trainer.train()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2171, in train
    return inner_training_loop(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 2531, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 3675, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/trainer.py", line 3731, in compute_loss
    outputs = model(**inputs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1353, in forward
    outputs = self.model(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1197, in forward
    encoder_outputs = self.encoder(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 741, in forward
    inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by JHW5981** [comment]
I didn’t actually solve this problem either; in the end, I just wrote parallel code myself for training.

**Comment by Koko12137** [comment]
> I didn’t actually solve this problem either; in the end, I just wrote parallel code myself for training.

maybe there are something wrong with your operations that indexing some vectors.

**Comment by zhiying318** [comment]
Hi, 

I'm also meeting this when trying to finetune **Gemma 3n** using 1 piece of A100.
I'm using `transformers==4.55.0`

Here is what I got:

```
Traceback (most recent call last):
  File "/workspace/train.py", line 177, in <module>
    run_training_phase(model, processor, cfg, train_dataloader, train_keys=["embed_tokens", "attn"], phase_name="embed_attn_continue", val_dataloader=val_dataloader)
  File "/workspace/train.py", line 134, in run_training_phase
    train_model(model, optimizer, cfg, train_dataloader, val_dataloader)
  File "/workspace/train.py", line 82, in train_model
    outputs = model(**batch.to(model.device))
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/models/gemma3n/modeling_gemma3n.py", line 2283, in forward
    outputs = self.model(
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/utils/generic.py", line 959, in wrapper
    output = func(self, *args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/models/gemma3n/modeling_gemma3n.py", line 2091, in forward
    image_features = self.get_image_features(pixel_values)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/models/gemma3n/modeling_gemma3n.py", line 1950, in get_image_features
    vision_outputs = self.vision_tower(
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/transformers/models/timm_wrapper/modeling_timm_wrapper.py", line 221, in forward
    last_hidden_state = self.timm_model.forward_features(pixel_values, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/timm/models/mobilenetv5.py", line 557, in forward_features
    x = self.conv_stem(x)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/timm/layers/conv_bn_act.py", line 83, in forward
    x = self.conv(x)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/.venv/lib/python3.10/site-packages/timm/layers/conv2d_same.py", line 53, in forward
    return conv2d_same(
  File "/workspace/.venv/lib/python3.10/site-packages/timm/layers/conv2d_same.py", line 28, in conv2d_same
    return F.conv2d(x, weight, bias, stride, (0, 0), dilation, groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
...
...
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [229,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [229,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [229,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [229,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [229,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

I found one possible solution to avoid this problem is to use Transformers version 4.46.3 [see here](https://github.com/AkariAsai/self-rag/issues/91#issuecomment-2568924642)

However, `Transformers==4.46.3` does not recognize the architecture of `Gemma 3n`, so it does not meet my need.

Do we have any other ways to fix this issue?

**Comment by ArthurZucker** [comment]
@zhiying318 do you have a small reproducer you could share? It's a bit hard for use to help otherwise!

**Comment by nivibilla** [comment]
I have the same issue, whats weird is the training loop ran perfectly fine for 75 steps and then fails with
```
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [80,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [81,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [82,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [83,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [84,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [85,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [86,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [14,0,0], thread: [87,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

This was from a GRPO run with TRL on llama 3.2 3b

**Comment by YcZhangSing** [comment]
I was also fine-tuning the Florence2 model on 4 4090s. I also trained for about 4k steps and then suddenly reported an error as the same. Do you know how to solve it?
