### ISSUE TITLE
GPTQ quantization throws an error with custom dataset but works perfectly fine on already existing ones.

### ISSUE THREAD

**Issue by manitadayon** [huggingface/transformers#34479]
### System Info

transformers: 4.45.2
huggingface-hub: 0.26.1
accelerate: 1.0.1
optimum: 1.23.1
auto-gptq: 0.7.1
bitsandbytes: 0.44.1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I can successfully quantize llama model using GPTQConfig given wikitext2 dataset, however the moment I switch to a custom dataset  (literally any custom dataset), I will get all sort of errors: Here is my setup:

```
custom_data = ['example1', example2', . . . , ]

config = GPTQConfig(bits = 4, dataset = custom_data (any list of string), tokenizer  = tokenizer, group_size = 128, desc_false = False, model_seq_len = 4096)
model = AutoModelForCausalLM.from_pretrained(model_path, quantization_config = config , device_map = 'auto')
```

This would give the error message of CUDA OOM, no matter size of data, what so ever. Like if I even choose two short data points.
Now if I get rid of device_map = 'auto' and set it as follows:

```
custom_data = ['example1', example2', . . . , ]

config = GPTQConfig(bits = 4, dataset = custom_data (any list of string), tokenizer  = tokenizer, group_size = 128, desc_false = False, model_seq_len = 4096)
model = AutoModelForCausalLM.from_pretrained(model_path, quantization_config = config , device_map =0)
```
I get the following error:

`Expected all tensors to be on the same device but got cpu and cuda
`
Removing the device_map = 'auto' also gives me the same error.

Now keeping everything the same but changing the dataset to wikitext2 works just fine. 
Wondering is there any problem with the custom data?  or is any way I can format my data to be understood by the package?

### Expected behavior

I expect according to documentation, the GPTQConfig works fine with custom dataset as long as the data is a list of string. BTW, I have enough resources in terms of memory & GPU, that I think CUDA OOM is not related to resource limitation.

**Comment by Rocketknight1** [comment]
cc @SunMarc @MekkCyber for quantization!

**Comment by MekkCyber** [comment]
Hey @manitadayon, what model are you trying to quantize ? and how much gpu memory do you have ? 
I am asking because this script works fine for me and you can find the result [here](https://huggingface.co/medmekk/Llama3.2-1B-GPTQ-4bits)
```
from transformers import GPTQConfig
from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "meta-llama/Llama-3.2-1B"

custom_data = ['example1', 'example2']

tokenizer = AutoTokenizer.from_pretrained(model_path)

config = GPTQConfig(bits = 4, dataset = custom_data, tokenizer=tokenizer, group_size = 128, desc_false = False, model_seq_len = 4096)
model = AutoModelForCausalLM.from_pretrained(model_path, quantization_config = config , device_map = 'auto')

model.push_to_hub('medmekk/Llama3.2-1B-GPTQ-4bits')
```

**Comment by manitadayon** [comment]
It is 2.0.1 (I can see this is not updated)

**Comment by MekkCyber** [comment]
I am using torch 2.5.1+cu121 (yes that's true it's strange about how it works with pre-existing data but I even tried on an other gpu and it works for me)

**Comment by manitadayon** [comment]
Thanks may I know about the format of your data? Is it like list of strings or something similar?

**Comment by MekkCyber** [comment]
Yeah it's a list of strings, I will try with Llama 3.1 70B next to see !

**Comment by MekkCyber** [comment]
@manitadayon, FYI I tried the 70B model with a list of two sentences and it works fine https://huggingface.co/medmekk/Llama3.1-70B-GPTQ-4bits

**Comment by manitadayon** [comment]
@MekkCyber wow, this is beyond strange, may I know the configuration of .from_pretrained since under one case which I originally mentioned I get expected tensor to be on the same device. 

Do you have device_map = 'auto', I am thinking it maybe my configuration for either GPTQConfig or from_pretrained.

**Comment by MekkCyber** [comment]
Well I used the very same GPTQConfig you shared in the issue description, and I used device_map = "auto", did you retry with an updated torch version ?

**Comment by manitadayon** [comment]
Trying to upgrade the torch version, now I get a problem with flash_attn. I think the problem might be this package since I did not mention the version before. My version is flash_attn = 2.3.6

**Comment by MekkCyber** [comment]
I didn't specify the attention implementation to be `flash_attention` so it's `SDPA` by default. But I don't understand do you get the error with `flash_attn` when trying to quantize with the same config you shared above ? If not can you share your exact code that's not working ?

**Comment by DebasishDhal** [comment]
> Hey [@manitadayon](https://github.com/manitadayon), what model are you trying to quantize ? and how much gpu memory do you have ? I am asking because this script works fine for me and you can find the result [here](https://huggingface.co/medmekk/Llama3.2-1B-GPTQ-4bits)
> 
> ```
> from transformers import GPTQConfig
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> model_path = "meta-llama/Llama-3.2-1B"
> 
> custom_data = ['example1', 'example2']
> 
> tokenizer = AutoTokenizer.from_pretrained(model_path)
> 
> config = GPTQConfig(bits = 4, dataset = custom_data, tokenizer=tokenizer, group_size = 128, desc_false = False, model_seq_len = 4096)
> model = AutoModelForCausalLM.from_pretrained(model_path, quantization_config = config , device_map = 'auto')
> 
> model.push_to_hub('medmekk/Llama3.2-1B-GPTQ-4bits')
> ```
> 
> I replicated the same env as you with the same versions

How would it work for a sequence-classification model?

**Comment by manitadayon** [comment]
@DebasishDhal , sorry for the late response, I made it to work, the problem was incompatibility of package versioning and that's why I was getting errors. My script was very similar to yours only with different parameters.

**Comment by DebasishDhal** [comment]
@manitadayon Correct me if I'm wrong.

Did you manage to get it working for sequence classification task? I don't think this is doable, but I'd be happy to look into the code. Can you post it here?
