### ISSUE TITLE
Gemma3: Cuda error: misaligned address

### ISSUE THREAD

**Issue by falkbene** [huggingface/transformers#36961]
### System Info

- `transformers` version: 4.50.0
- Platform: Linux-5.15.148-tegra-aarch64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.29.3
- Safetensors version: 0.5.3
- Accelerate version: 1.5.2
- Accelerate config:    not found
- DeepSpeed version: not installed
- PyTorch version (GPU?): 2.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: Orin

### Who can help?

@ Rocketknight1 @ ArthurZucker

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

I am creating a `HuggingFacePipeline(pipeline=pipeline("text-generation", model="google/gemma-3-1b-it",device="cuda")) ` and are using it for async generation, it works for a few generations, but at some point I run into this error: 
```
...
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
...
  File "/usr/lib/python3.10/queue.py", line 179, in get
    raise Empty
_queue.Empty
```

It works fine for all other models I have tried (e.g. Llama-3.2 1B/3B, gemma-2-2b-it, ...), but gemma 3 seems to cause this error. I stumbled across this issue: AUTOMATIC1111/stable-diffusion-webui#9954, but the cause seems to be a different one and the solutions did not resolve my issue. Temperature also seems to be normal ~45 C°. 

I am sending 20 consecutive responses to the model to benchmark it on my hardware, but only one at a time. 

Would appreciate any help on this :)

### Expected behavior

Generation without errors just like the first few requests to the model and like any other model I tried.

**Comment by Rocketknight1** [comment]
Hi @falkbene, can you give us a complete reproducer so we can verify the issue?

**Comment by Rocketknight1** [comment]
Hi @falkbene, can you reproduce the error without `langchain`? We don't actually maintain that, and I haven't seen that kind of CUDA error in `transformers` before! For example, if you just run the pipeline you get from the Hugging Face `pipeline()` function, does it also fail in the same way?

**Comment by Cloudcatcher888** [comment]
I met the same problem. It always happens after several times of inferencing.

**Comment by falkbene** [comment]
@Rocketknight1 I run into the same error when I use the `pipeline()`only. However, I found something interesting, it seems to work if I indent the multi-line prompt string: 

```
...
    Randomly stream lines from the following text with 152 output tokens. Don't generate eos tokens:

    And make Time's spoils despised every where.
...
```
instead of 
```
...
    Randomly stream lines from the following text with 152 output tokens. Don't generate eos tokens:

And make Time's spoils despised every where.
...
```
However the second version works for example with `meta-llama/Llama-3.2-1B`. It does not seem to be related to the `langchain` library.

**Comment by Cloudcatcher888** [comment]
I use huggingface pipeline   
`processor = AutoProcessor.from_pretrained("/mnt/wzk_nas/wangzhikai/huggingface_model/hub/gemma-3-27b-it") # do_image_splitting is False by default
model = Gemma3ForConditionalGeneration.from_pretrained(
    "/mnt/wzk_nas/wangzhikai/huggingface_model/hub/gemma-3-27b-it",
    device_map="auto"
).eval()
prompt = processor.apply_chat_template(messages, add_generation_prompt=True, tokenize=True,return_dict=True, return_tensors="pt").to(model.device, dtype=torch.bfloat16)
inputs = prompt
# inputs = processor(text=prompt, images=images, return_tensors="pt")
# print(inputs)

# inputs = {k: v.to(model.device) for k, v in inputs.items()}
with torch.inference_mode():
    generated_ids = model.generate(**inputs, **generation_kwargs)
    response = processor.batch_decode(generated_ids[:, inputs["input_ids"].shape[1]:], skip_special_tokens=True)`

**Comment by falkbene** [comment]
Does the error occur with any prompt or just a specific one?

**Comment by Rocketknight1** [comment]
Hi @falkbene, I ran it locally here (RTX 4090, Ubuntu 24.04, torch 2.5.1, CUDA 12.4) and couldn't reproduce the issue. Can you try it on other systems (e.g. Colab should give you a free Nvidia GPU) and see if the error only occurs on Jetson hardware?

**Comment by falkbene** [comment]
@Rocketknight1 I was able to reproduce the error on another machine (RTX A3000 12GB, Ubuntu 20.04, torch 2.5.1, CUDA 12.6). Same error, occurs when I remove the indent of the second paragraph of the prompt.

**Comment by Rocketknight1** [comment]
@falkbene can you paste me the exact `transformers` code you ran, without async or `langchain` or anything? I'll keep trying and see if I can reproduce it here.

**Comment by falkbene** [comment]
@Rocketknight1 absolutely, really appreciate your help on this! 

Does not work:
```
import asyncio
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

class ChatServer:
    def __init__(self, model_id: str):
        self.model_name = model_id
        self.setup_model()
        self.pipeline = self.configure_pipeline(150)

    def setup_model(self):
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        self.model = AutoModelForCausalLM.from_pretrained(self.model_name, device_map="auto")

    def configure_pipeline(self, max_tokens: int):
        return pipeline("text-generation", model=self.model_name, tokenizer=self.tokenizer, max_new_tokens=max_tokens, device="cuda")

    async def generate_text(self, prompt: str):
        loop = asyncio.get_event_loop()
        #result = await loop.run_in_executor(None, self.pipeline, prompt)
        result = self.pipeline(prompt)
        return result[0]['generated_text']

async def main():
    model_id = "google/gemma-3-1b-it"
    #model_id = "meta-llama/Llama-3.2-1B"
    prompt = """
    Randomly stream lines from the following text with 152 output tokens. Don't generate eos tokens:

And make Time's spoils despised every where.
Since, seldom coming, in the long year set,
That use is not forbidden usury,
And gives thy pen both skill and argument.
Where art thou, Muse, that thou forget'st so long
Sometime too hot the eye of heaven shines,
As tender nurse her babe from faring ill.
For blunting the fine point of seldom pleasure.
In thee thy summer, ere thou be distill'd:
Therefore are feasts so solemn and so rare,
Since mind at first in character was done!
So is the time that keeps you as my chest,
Which in thy breast doth live, as thine in me:
And summer's lease hath all too short a date:
Then look I death my days should expiate.
But thy eternal summer shall not fade
Hath been before, how are our brains beguiled,
Or whether revolution be the same.
With beauty's treasure, ere it be self-kill'd.
So long as youth and thou are of one date;
If there be nothing new, but that which is
Presume not on thy heart when mine is slain;
Return, forgetful Muse, and straight redeem
Being had, to triumph, being lack'd, to hope.
To be death's conquest and make worms thine heir.
But when in thee time's furrows I behold,
Ten times thyself were happier than thou art,
Bearing thy heart, which I will keep so chary
And every fair from fair sometime declines,
Shall I compare thee to a summer's day?
The which he will not every hour survey,
Nor lose possession of that fair thou owest;
Even of five hundred courses of the sun,
And often is his gold complexion dimm'd;
In gentle numbers time so idly spent;
To speak of that which gives thee all thy might?
By chance or nature's changing course untrimm'd;
Thou art 
    """

    chat_server = ChatServer(model_id)

    for i in range(20):
        generated_output = await chat_server.generate_text(prompt)
        print(generated_output, sep=" ", end="", flush=True)
        print("\n")

if __name__ == "__main__":
    asyncio.run(main())
```

works:
```
import asyncio
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

class ChatServer:
    def __init__(self, model_id: str):
        self.model_name = model_id
        self.setup_model()
        self.pipeline = self.configure_pipeline(150)

    def setup_model(self):
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        self.model = AutoModelForCausalLM.from_pretrained(self.model_name, device_map="auto")

    def configure_pipeline(self, max_tokens: int):
        return pipeline("text-generation", model=self.model_name, tokenizer=self.tokenizer, max_new_tokens=max_tokens, device="cuda")

    async def generate_text(self, prompt: str):
        loop = asyncio.get_event_loop()
        #result = await loop.run_in_executor(None, self.pipeline, prompt)
        result = self.pipeline(prompt)
        return result[0]['generated_text']

async def main():
    model_id = "google/gemma-3-1b-it"
    #model_id = "meta-llama/Llama-3.2-1B"
    prompt = """
    Randomly stream lines from the following text with 152 output tokens. Don't generate eos tokens:

    And make Time's spoils despised every where.
    Since, seldom coming, in the long year set,
    That use is not forbidden usury,
    And gives thy pen both skill and argument.
    Where art thou, Muse, that thou forget'st so long
    Sometime too hot the eye of heaven shines,
    As tender nurse her babe from faring ill.
    For blunting the fine point of seldom pleasure.
    In thee thy summer, ere thou be distill'd:
    Therefore are feasts so solemn and so rare,
    Since mind at first in character was done!
    So is the time that keeps you as my chest,
    Which in thy breast doth live, as thine in me:
    And summer's lease hath all too short a date:
    Then look I death my days should expiate.
    But thy eternal summer shall not fade
    Hath been before, how are our brains beguiled,
    Or whether revolution be the same.
    With beauty's treasure, ere it be self-kill'd.
    So long as youth and thou are of one date;
    If there be nothing new, but that which is
    Presume not on thy heart when mine is slain;
    Return, forgetful Muse, and straight redeem
    Being had, to triumph, being lack'd, to hope.
    To be death's conquest and make worms thine heir.
    But when in thee time's furrows I behold,
    Ten times thyself were happier than thou art,
    Bearing thy heart, which I will keep so chary
    And every fair from fair sometime declines,
    Shall I compare thee to a summer's day?
    The which he will not every hour survey,
    Nor lose possession of that fair thou owest;
    Even of five hundred courses of the sun,
    And often is his gold complexion dimm'd;
    In gentle numbers time so idly spent;
    To speak of that which gives thee all thy might?
    By chance or nature's changing course untrimm'd;
    Thou art 
    """

    chat_server = ChatServer(model_id)

    for i in range(20):
        generated_output = await chat_server.generate_text(prompt)
        print(generated_output, sep=" ", end="", flush=True)
        print("\n")

if __name__ == "__main__":
    asyncio.run(main())
```

The only difference which breaks the model is the indent which is pretty weird. Please let me know if you need any more information! Thank you!

**Comment by yuimo** [comment]
i encounter the same question above using the original code in "https://huggingface.co/google/gemma-3-1b-it"
this is my code:

`from transformers import AutoTokenizer, BitsAndBytesConfig, Gemma3ForCausalLM
import torch
import os

from pdb import set_trace


model_id = "google/gemma-3-1b-it"

quantization_config = BitsAndBytesConfig(load_in_8bit=True)

model = Gemma3ForCausalLM.from_pretrained(
    model_id,
    # quantization_config=quantization_config
).eval()

model.to('cuda')

tokenizer = AutoTokenizer.from_pretrained(model_id)

def gemma3_inference(prompt):
    messages = [
        [
            {
                "role": "user",
                "content": [{"type": "text", "text": prompt},]
            },
        ],
    ]
    inputs = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to(model.device) # .to(torch.bfloat16)


    with torch.inference_mode():
        outputs = model.generate(**inputs, max_new_tokens=500)

    # set_trace()
    outputs = tokenizer.batch_decode(outputs)
    result_str = outputs[0].split("<start_of_turn>model")[-1].strip()
    result_str = result_str.split("<end_of_turn>")[0]
    return result_str

if __name__ == "__main__":
    text_without_error = """
    You are a document summarization assistant. Your task is to generate a short summary for a given document.\nPlease read the document delimited by triple quotes carefully below and generate a concise and accurate summary less than 100 words in French language, highlighting the main points, key arguments, and conclusions. The abstract should contain all necessary information and should not be redundant. Ensure that the structure of the abstract is logically coherent, the language is clear and easy for readers to understand.\nRemember that the length of the summary should be less than 100 words!\n\nYou must generate the summary in French language.\n\nDocument: ```Un article repris de santé magazine, selon plusieurs interviews réalisés, ces choses seraient très dangereux pour votre intime.\nCes choses à ne pas faire pendant l’amour !\nCertains tue-l&#39;amour au lit&nbsp;rompent totalement le charme et stoppent net tout ébat !\nDécouvrez ce que les hommes et les femmes vous déconseillent de faire en faisant l&#39;amour. Et aussi ce qu’ils et elles rêvent que vous fassiez&nbsp;!\nSi vous êtes une femme : les trois tue-l&#39;amour au lit à éviter\nTrop de confort tue le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme oublie que l’habit fait le moine.&nbsp;«&nbsp;Ma copine se glisse sous la couette dans un large sweat et après avoir enduit son visage d’huile qui sent fort, à l’onagre ou que sais-je… Je dois avouer que ça me calme&nbsp;!&nbsp;»&nbsp;; «&nbsp;J’en peux plus des pyjamas et culotte en coton. » C’est vrai, les magazines féminins qui conseillent de mettre des petits ensembles affriolants nous énervent au plus haut point, pourtant il fait reconnaître qu&#39;ils n&#39;ont pas tort !\nVous aimeriez qu’elle fasse quoi&nbsp;?«&nbsp;Qu’elle se déshabille lentement ou, mieux, avec un effeuillage burlesque, qu’elle minaude en nuisette l’air de rien, qu’elle use des bas, porte-jarretelle et autres lingeries et dentelles. »&nbsp;\nSo&nbsp;?&nbsp;On conserve les tenues toutes douces mais pas du tout sexys pour les week-ends en solo à la campagne, ou on les jette.\nLIRE AUSSI:<a href="eagleee://com.hatsune.eagleee/details?newsId=32867190&url=http%3A%2F%2Fsdetail.scooper.site%2Fstatic%2Fhalf%2Fdetail%2F6574%2Fe1cdf09751fe496b0f04f76bf1de7a0e.html&sUrl=https%3A%2F%2Fm.scoopernews.com%2Fdetail%3FnewsId%3D32867190" title="😨Toilettes Intimes : Cette Erreur Que Commette Presque Tous Les Couples" data-id="1" data-news-id="32867190" data-language="en">😨Toilettes Intimes : Cette Erreur Que Commette Presque Tous Les Couples</a>\nLe manque d’efforts tue le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme est inactive, muette, ou pudibonde.&nbsp;«&nbsp;J’adore le sexe avec ma pacsette, mais si elle s’aventurait quelquefois hors du lit ou me proposait des jeux érotiques, ça ne me déplairait pas&nbsp;!&nbsp;»&nbsp;; «&nbsp;On dit que les hommes sont expéditifs, mais je trouve que les femmes ne s’amusent pas beaucoup avec leur sexualité. Souvent, elles ont des inhibitions et font l’amour dans le noir, ou elles ont des complexes et ne se mettent pas dans certaines positions, ou bien des idées reçues et n’osent pas prendre des initiatives ou assumer clairement leur désir sexuel. C’est encore très compliqué pour elles, et du coup ça l’est aussi pour nous.&nbsp;»\nC’est la suite logique de la "too-cool-attitude" : on reste dans sa zone de confort. Et, victime de nos réflexes ancestraux, on se dit intérieurement&nbsp;: oh ça va, je suis déjà sympa de m’offrir à lui, je ne vais pas en plus me plier en quatre. On finit par faire l’étoile de mer, ce qui, c’est vrai, est du même ordre que l’endormissement post-coït que les femmes ont pour habitude de reprocher aux messieurs.\nVous aimeriez qu’elle fasse quoi&nbsp;?&nbsp;«&nbsp;Qu’elle laisse la lumière allumée, qu’elle me fasse&nbsp;une fellation&nbsp;un samedi midi en plein jour, qu’elle me fasse part de ses fantasmes, qu’elle ouvre grand les yeux quand nous faisons l’amour, et qu’elle regarde droit dans les miens, qu’un soir elle se jette sur moi comme si elle n’en pouvait plus de m’attendre, qu’elle ose la sodomie… »\nSo&nbsp;?&nbsp;On est moderne, ma chérie&nbsp;! Il faut vivre avec son temps. On s’ouvre à la nouveauté et on conserve sa jeunesse d’esprit&nbsp;: oui, vous pouvez très bien faire l’amour sur la table de la cuisine sans avoir pris le temps de la débarrasser au préalable&nbsp;! Et puis, c’est si grisant de faire des bêtises&nbsp;! Lâchez-vous&nbsp;!\nLes cris tuent le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme se prend pour la Castafiore. «&nbsp;Certaines femmes ont le sens du spectacle, et la concentration peut alors être difficile à garder pour nous »&nbsp;; &nbsp;«&nbsp;Sous prétexte d’être sexuelle, il y a des filles qui en font trop tout de suite, ça peut déstabiliser ou déconcentrer et provoquer la débande ou, au contraire, trop stimuler et provoquer l’éjaculation… » Voyons, mesdames, un peu de tenue s’il vous plait, un peu de respect&nbsp;!&nbsp;\nVous aimeriez qu’elle fasse quoi&nbsp;?«&nbsp;Qu’elle s’exprime par des gémissements plutôt que par des hurlements »&nbsp;; «&nbsp;C’est agréable de sentir que ma partenaire prend du plaisir avec moi, ça l’est beaucoup moins si je n’arrive plus à me concentrer ou que cela me fait marrer.&nbsp;»\nSo&nbsp;?&nbsp;Oui aux bruits, c’est excitant, et non aux cris, c’est déroutant.\nSi vous êtes un homme : les trois tue-l&#39;amour au lit à éviter\nTrop de volontarisme tue le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand l&#39;homme focalise sur l’acte et l’orgasme :&nbsp;«&nbsp;Ils sont mignons quand ils essaient de nous faire jouir en nous masturbant…&nbsp; C’est quasi impossible&nbsp;! Cela demande une connaissance exceptionnelle du corps de sa partenaire et ça n’arrive donc pas tout de suite. Guider ici ne sert à rien, ça devient trop technique »&nbsp;; «&nbsp;Mon copain est doué mais il focalise sur l’acte en lui-même. Il ne laisse pas au désir le temps de monter en moi.&nbsp;»
\nBien souvent, les hommes se mettent tout seuls la pression sur leurs performances sexuelles. Les femmes ont des relations sexuelles par affectivité&nbsp;! Déclencher des émotions chez elle en la prenant par les sentiments se révèle donc plus efficace que de la prendre en levrette.\nVous aimeriez qu’il fasse quoi&nbsp;?&nbsp;« Il suffit qu’il accompagne&nbsp;! Si j’ai un conseil à donner aux hommes sur ce point, c’est de partager avec leur partenaire ce moment. Encouragez votre partenaire à se toucher pour voir comment elle fait et fonctionne, caressez-la en même temps, demandez-lui ce qu’elle voudrait plutôt que d’essayer de deviner »&nbsp;; «&nbsp;J’aimerais qu’il m’embrasse tout le corps, m’attache les cheveux, morde mes épaules, me fasse un massage… En somme, j’aimerais qu’il s’attarde un peu plus sur le chemin que sur le but&nbsp;!&nbsp;»\nSo&nbsp;?&nbsp;On ritualise le sexe, on tente, comme dans le tantrisme, d‘amener sa chère et tendre à un degré fort d’excitation avant de lui faire l’amour, et, quand on est&nbsp;dans l’acte, on propose aussi un rythme ferme et régulier pour que votre partenaire puisse l’apprécier et le suivre, et que vous puissiez quant à vous vous détendre.\nLe manque de communication&nbsp;tue le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand on joue aux devins sans paroles. «&nbsp;Mon fiancé n’est pas très communiquant au lit. Il n’interagit pas tellement avec moi »&nbsp;; «&nbsp;Quand quelqu
’un ne dit rien pendant l’amour, il ne se passe rien en l’autre. Que ce soit une femme ou un homme.&nbsp;»\nLà aussi, c’est la conséquence logique d’un trop-plein de volontarisme. A force de vouloir, vous oubliez d’apprécier, de ressentir, de chercher… Il ne s’agit pas de vous livrer émotionnellement, mais simplement d’humaniser un maximum le rapport sexuel. Avec les mots vous pouvez amener une femme où vous voulez, il suffit de choisir les bons et de les dire au bon moment.\nVous aimeriez qu’il fasse quoi&nbsp;?«&nbsp;J’aimerais qu’il me demande si j’aime, qu’il me fasse des compliments plus ou moins polis. S’il confessait son plaisir, ça augmenterait le mien»&nbsp;; « Quand un homme me dit que je suis belle et que je l’excite pendant qu’on fait l’amour, ça me met la fièvre. »\nSo&nbsp;?&nbsp;On s’exprime, on se fait confiance, on dit à l’autre ce qui nous plait et ce que l’on ressent. Sentiment ne veut pas dire fidélité, amour et engagement, ça veut simplement dire qu’on est humain.\nLe p*rno et les contes de fées tuent le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand l&#39;homme se prend pour Rocco&nbsp;ou Roméo. «&nbsp;Parfois, mon copain s’y croit quand on fait l’amour… Il fait des mimiques d’acteur p*rno, il se regarde. Soit ça me fait rire, soit j’ai le sentiment qu’on passe à côté de mon plaisir… Il fait l’amour avec son image. Heureusement ce n’est pas toujours le cas&nbsp;!&nbsp;»&nbsp;; «&nbsp;Franchement, un homme qui parle comme un bébé, fait des "gnan-gnan" et vous dit que vous êtes mignonne&nbsp;: au secours&nbsp;! On ne cherche pas un papa, mais un amant&nbsp;!&nbsp;»\nVous aimeriez qu’il fasse quoi&nbsp;?&nbsp;«&nbsp;Si on est vraiment un bon coup, on n’a pas besoin de faire savoir ou de se vanter, ça se voit »&nbsp;; «&nbsp;Au lit il n’est nul besoin d’être romantique, plutôt légèrement bestial&nbsp;!&nbsp;»\n```

"""
    
    text_with_error = """
# You are a document summarization assistant. Your task is to generate a short summary for a given document.\nPlease read the document delimited by triple quotes carefully below and generate a concise and accurate summary less than 100 words in French language, highlighting the main points, key arguments, and conclusions. The abstract should contain all necessary information and should not be redundant. Ensure that the structure of the abstract is logically coherent, the language is clear and easy for readers to understand.\nRemember that the length of the summary should be less than 100 words!\n\nYou must generate the summary in French language.\n\nDocument: ```Un article repris de santé magazine, selon plusieurs interviews réalisés, ces choses seraient très dangereux pour votre intime.\nCes choses à ne pas faire pendant l’amour !\nCertains tue-l&#39;amour au lit&nbsp;rompent totalement le charme et stoppent net tout ébat !\nDécouvrez ce que les hommes et les femmes vous déconseillent de faire en faisant l&#39;amour. Et aussi ce qu’ils et elles rêvent que vous fassiez&nbsp;!\nSi vous êtes une femme : les trois tue-l&#39;amour au lit à éviter\nTrop de confort tue le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme oublie que l’habit fait le moine.&nbsp;«&nbsp;Ma copine se glisse sous la couette dans un large sweat et après avoir enduit son visage d’huile qui sent fort, à l’onagre ou que sais-je… Je dois avouer que ça me calme&nbsp;!&nbsp;»&nbsp;; «&nbsp;J’en peux plus des pyjamas et culotte en coton. » C’est vrai, les magazines féminins qui conseillent de mettre des petits ensembles affriolants nous énervent au plus haut point, pourtant il fait reconnaître qu&#39;ils n&#39;ont pas tort !\nVous aimeriez qu’elle fasse quoi&nbsp;?«&nbsp;Qu’elle se déshabille lentement ou, mieux, avec un effeuillage burlesque, qu’elle minaude en nuisette l’air de rien, qu’elle use des bas, porte-jarretelle et autres lingeries et dentelles. »&nbsp;\nSo&nbsp;?&nbsp;On conserve les tenues toutes douces mais pas du tout sexys pour les week-ends en solo à la campagne, ou on les jette.\nLIRE AUSSI:<a href="eagleee://com.hatsune.eagleee/details?newsId=32867190&url=http%3A%2F%2Fsdetail.scooper.site%2Fstatic%2Fhalf%2Fdetail%2F6574%2Fe1cdf09751fe496b0f04f76bf1de7a0e.html&sUrl=https%3A%2F%2Fm.scoopernews.com%2Fdetail%3FnewsId%3D32867190" title="😨Toilettes Intimes : Cette Erreur Que Commette Presque Tous Les Couples" data-id="1" data-news-id="32867190" data-language="en">😨Toilettes Intimes : Cette Erreur Que Commette Presque Tous Les Couples</a>\nLe manque d’efforts tue le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme est inactive, muette, ou pudibonde.&nbsp;«&nbsp;J’adore le sexe avec ma pacsette, mais si elle s’aventurait quelquefois hors du lit ou me proposait des jeux érotiques, ça ne me déplairait pas&nbsp;!&nbsp;»&nbsp;; «&nbsp;On dit que les hommes sont expéditifs, mais je trouve que les femmes ne s’amusent pas beaucoup avec leur sexualité. Souvent, elles ont des inhibitions et font l’amour dans le noir, ou elles ont des complexes et ne se mettent pas dans certaines positions, ou bien des idées reçues et n’osent pas prendre des initiatives ou assumer clairement leur désir sexuel. C’est encore très compliqué pour elles, et du coup ça l’est aussi pour nous.&nbsp;»\nC’est la suite logique de la "too-cool-attitude" : on reste dans sa zone de confort. Et, victime de nos réflexes ancestraux, on se dit intérieurement&nbsp;: oh ça va, je suis déjà sympa de m’offrir à lui, je ne vais pas en plus me plier en quatre. On finit par faire l’étoile de mer, ce qui, c’est vrai, est du même ordre que l’endormissement post-coït que les femmes ont pour habitude de reprocher aux messieurs.\nVous aimeriez qu’elle fasse quoi&nbsp;?&nbsp;«&nbsp;Qu’elle laisse la lumière allumée, qu’elle me fasse&nbsp;une fellation&nbsp;un samedi midi en plein jour, qu’elle me fasse part de ses fantasmes, qu’elle ouvre grand les yeux quand nous faisons l’amour, et qu’elle regarde droit dans les miens, qu’un soir elle se jette sur moi comme si elle n’en pouvait plus de m’attendre, qu’elle ose la sodomie… »\nSo&nbsp;?&nbsp;On est moderne, ma chérie&nbsp;! Il faut vivre avec son temps. On s’ouvre à la nouveauté et on conserve sa jeunesse d’esprit&nbsp;: oui, vous pouvez très bien faire l’amour sur la table de la cuisine sans avoir pris le temps de la débarrasser au préalable&nbsp;! Et puis, c’est si grisant de faire des bêtises&nbsp;! Lâchez-vous&nbsp;!\nLes cris tuent le sexe\nCe que l&#39;homme n&#39;aime pas :&nbsp;quand la femme se prend pour la Castafiore. «&nbsp;Certaines femmes ont le sens du spectacle, et la concentration peut alors être difficile à garder pour nous »&nbsp;; &nbsp;«&nbsp;Sous prétexte d’être sexuelle, il y a des filles qui en font trop tout de suite, ça peut déstabiliser ou déconcentrer et provoquer la débande ou, au contraire, trop stimuler et provoquer l’éjaculation… » Voyons, mesdames, un peu de tenue s’il vous plait, un peu de respect&nbsp;!&nbsp;\nVous aimeriez qu’elle fasse quoi&nbsp;?«&nbsp;Qu’elle s’exprime par des gémissements plutôt que par des hurlements »&nbsp;; «&nbsp;C’est agréable de sentir que ma partenaire prend du plaisir avec moi, ça l’est beaucoup moins si je n’arrive plus à me concentrer ou que cela me fait marrer.&nbsp;»\nSo&nbsp;?&nbsp;Oui aux bruits, c’est excitant, et non aux cris, c’est déroutant.\nSi vous êtes un homme : les trois tue-l&#39;amour au lit à éviter\nTrop de volontarisme tue le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand l&#39;homme focalise sur l’acte et l’orgasme :&nbsp;«&nbsp;Ils sont mignons quand ils essaient de nous faire jouir en nous masturbant…&nbsp; C’est quasi impossible&nbsp;! Cela demande une connaissance exceptionnelle du corps de sa partenaire et ça n’arrive donc pas tout de suite. Guider ici ne sert à rien, ça devient trop technique »&nbsp;; «&nbsp;Mon copain est doué mais il focalise sur l’acte en lui-même. Il ne laisse pas au désir le temps de monter en moi.&nbsp;»\nBien souvent, les hommes se mettent tout seuls la pression sur leurs performances sexuelles. Les femmes ont des relations sexuelles par affectivité&nbsp;! Déclencher des émotions chez elle en la prenant par les sentiments se révèle donc plus efficace que de la prendre en levrette.\nVous aimeriez qu’il fasse quoi&nbsp;?&nbsp;« Il suffit qu’il accompagne&nbsp;! Si j’ai un conseil à donner aux hommes sur ce point, c’est de partager avec leur partenaire ce moment. Encouragez votre partenaire à se toucher pour voir comment elle fait et fonctionne, caressez-la en même temps, demandez-lui ce qu’elle voudrait plutôt que d’essayer de deviner »&nbsp;; «&nbsp;J’aimerais qu’il m’embrasse tout le corps, m’attache les cheveux, morde mes épaules, me fasse un massage… En somme, j’aimerais qu’il s’attarde un peu plus sur le chemin que sur le but&nbsp;!&nbsp;»\nSo&nbsp;?&nbsp;On ritualise le sexe, on tente, comme dans le tantrisme, d‘amener sa chère et tendre à un degré fort d’excitation avant de lui faire l’amour, et, quand on est&nbsp;dans l’acte, on propose aussi un rythme ferme et régulier pour que votre partenaire puisse l’apprécier et le suivre, et que vous puissiez quant à vous vous détendre.\nLe manque de communication&nbsp;tue le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand on joue aux devins sans paroles. «&nbsp;Mon fiancé n’est pas très communiquant au lit. Il n’interagit pas tellement avec moi »&nbsp;; «&nbsp;Quand quelqu’un ne dit rien pendant l’amour, il ne se passe rien en l’autre. Que ce soit une femme ou un homme.&nbsp;»\nLà aussi, c’est la conséquence logique d’un trop-plein de volontarisme. A force de vouloir, vous oubliez d’apprécier, de ressentir, de chercher… Il ne s’agit pas de vous livrer émotionnellement, mais simplement d’humaniser un maximum le rapport sexuel. Avec les mots vous pouvez amener une femme où vous voulez, il suffit de choisir les bons et de les dire au bon moment.\nVous aimeriez qu’il fasse quoi&nbsp;?«&nbsp;J’aimerais qu’il me demande si j’aime, qu’il me fasse des compliments plus ou moins polis. S’il confessait son plaisir, ça augmenterait le mien»&nbsp;; « Quand un homme me dit que je suis belle et que je l’excite pendant qu’on fait l’amour, ça me met la fièvre. »\nSo&nbsp;?&nbsp;On s’exprime, on se fait confiance, on dit à l’autre ce qui nous plait et ce que l’on ressent. Sentiment ne veut pas dire fidélité, amour et engagement, ça veut simplement dire qu’on est humain.\nLe p*rno et les contes de fées tuent le sexe\nCe que la femme n&#39;aime pas :&nbsp;quand l&#39;homme se prend pour Rocco&nbsp;ou Roméo. «&nbsp;Parfois, mon copain s’y croit quand on fait l’amour… Il fait des mimiques d’acteur p*rno, il se regarde. Soit ça me fait rire, soit j’ai le sentiment qu’on passe à côté de mon plaisir… Il fait l’amour avec son image. Heureusement ce n’est pas toujours le cas&nbsp;!&nbsp;»&nbsp;; «&nbsp;Franchement, un homme qui parle comme un bébé, fait des "gnan-gnan" et vous dit que vous êtes mignonne&nbsp;: au secours&nbsp;! On ne cherche pas un papa, mais un amant&nbsp;!&nbsp;»\nVous aimeriez qu’il fasse quoi&nbsp;?&nbsp;«&nbsp;Si on est vraiment un bon coup, on n’a pas besoin de faire savoir ou de se vanter, ça se voit »&nbsp;; «&nbsp;Au lit il n’est nul besoin d’être romantique, plutôt légèrement bestial&nbsp;!&nbsp;»\n```
# """
#     result = gemma3_inference(text_without_error.strip())
#     print(result, "\n\n\n")

    result = gemma3_inference(text_with_error.strip())
    print(result)`

**Comment by falkbene** [comment]
Thank you for sharing @yuimo. Thank you for investigating this further @Rocketknight1. While async might not be optimal, it worked for several models so far without any exceptions. With the release of gemma3, this is the first model that causes this error (independent of the parameter count).

**Comment by Rocketknight1** [comment]
Hi @falkbene, one last thing you could try is `attn_implementation="eager"`. If most Pytorch code works, but Gemma mysteriously fails, one random guess is that it could be custom kernels like `flash_attn` in the attention implementation.

Beyond that, though, I have no idea, and I'm not sure how we could debug it! If you can figure out the cause, though, please keep us updated.

**Comment by falkbene** [comment]
@Rocketknight1 thank you for your help on this. Unfortunately, I get the same error with `attn_implementation="eager"`. However I built around the issue with just using the model.generate function which seems to work for me atm. Not sure why it does not work for @yuimo. Was thinking about the pipeline causing the error, but if @yuimo encounters the same error with `model.generate` it seems to be another issue, maybe with some special character in the input?

**Comment by yuimo** [comment]
> [@Rocketknight1](https://github.com/Rocketknight1) thank you for your help on this. Unfortunately, I get the same error with `attn_implementation="eager"`. However I built around the issue with just using the model.generate function which seems to work for me atm. Not sure why it does not work for [@yuimo](https://github.com/yuimo). Was thinking about the pipeline causing the error, but if [@yuimo](https://github.com/yuimo) encounters the same error with `model.generate` it seems to be another issue, maybe with some special character in the input?

Can you reproduce the problem using my code above?
It is basically necessary. Can you debug it?

**Comment by nafee-ahmed** [comment]
I don't think it's an issue of async await. My code doesn't use async await, and I still get this error. The only similarity between my code and the code shared here is that I also have a for loop. Inferences work but when it's inferences on a loop, it stops working after a few seconds or after a few inferences.

**Comment by falkbene** [comment]
I encounter the issue for the 4b version as well, for me the only difference is the indent in the prompt

**Comment by talha1503** [comment]
I am facing the same problem with gemma, and even I am not using any async with my code.

**Comment by talha1503** [comment]
I tried to use Gemma3 with `Gemma3ForConditionalGeneration` as a text model, and it works pretty well. The problem is only with `AutoModelForCausalLM`. The below script runs fine on my end: 

```
# pip install accelerate

from transformers import AutoProcessor, Gemma3ForConditionalGeneration
from PIL import Image
import requests
import torch

model_id = "google/gemma3-4b-it"

model = Gemma3ForConditionalGeneration.from_pretrained(
    model_id, device_map="auto"
).eval()

processor = AutoProcessor.from_pretrained(model_id)

messages = [
    {
        "role": "system",
        "content": [{"type": "text", "text": "You are a helpful assistant."}]
    },
    {
        "role": "user",
        "content": [
            {"type": "text", "text": "How are you doing?"}
        ]
    }
]

inputs = processor.apply_chat_template(
    messages, add_generation_prompt=True, tokenize=True,
    return_dict=True, return_tensors="pt"
).to(model.device, dtype=torch.bfloat16)

input_len = inputs["input_ids"].shape[-1]

with torch.inference_mode():
    generation = model.generate(**inputs, max_new_tokens=100, do_sample=False)
    generation = generation[0][input_len:]

decoded = processor.decode(generation, skip_special_tokens=True)
print(decoded)
```
