### ISSUE TITLE
🐛 [BART] Pipeline OOM 

### ISSUE THREAD

**Issue by Colanim** [huggingface/transformers#4779]
# 🐛 Bug

I try to run BART model myself versus running the model through `pipeline`.

Running the BART model myself is fine, but I have OOM on my GPU if I try to run the same model through pipeline.

Please see the following code : https://gist.github.com/Colanim/4fae6ab52c05716062a0f20c4a6b9737

_(It assume you have a file `cnndm/test.source` with an article on each line)_

Run with : 
`python pipeline_oom.py --model HuggingFace --batch-size 32`  
(Should **not** produce OOM on 11G-GPU)

and `python pipeline_oom.py --model Pipeline --batch-size 32`  
(Should produce OOM on 11G-GPU)

---

**Why the pipeline use more memory ?**

@sshleifer

**Comment by Colanim** [comment]
@sshleifer Can you reproduce ?

**Comment by sshleifer** [comment]
OK I figured out the problem
Long articles are not getting truncated anymore by pipeline.
Will have a look.
If you look at the second val.source example it's 1583 tokens, and pipeline does not truncated it, whereas `Huggingface` does.

Related: #4236

**Comment by Colanim** [comment]
May be related #5398
