### ISSUE TITLE
Regarding GPU use for LM

### ISSUE THREAD

**Issue by shubhujf** [huggingface/transformers#6483]
# ❓ Questions & Help

## Details

**A link to original question on the forum/Stack Overflow**:

**Comment by shubhujf** [comment]
Hi,
I am running example given in README.md of language_modeling using following command:
export TRAIN_FILE=/path/to/dataset/wiki.train.raw
export TEST_FILE=/path/to/dataset/wiki.test.raw

python run_language_modeling.py \
    --output_dir=output \
    --model_type=gpt2 \
    --model_name_or_path=gpt2 \
    --do_train \
    --train_data_file=$TRAIN_FILE \
    --do_eval \
    --eval_data_file=$TEST_FILE

It has started training but it is not using GPU (TITAN X) at all, when I see throug nvidia-smi command 
I am new to this So Can you please let me know if I'm missing anything here.

Thanks.

**Comment by LysandreJik** [comment]
This is probably because torch doesn't detect that you have a GPU. Can you try launching a python console and running the following?

```py
import torch
print(torch.cuda.is_available())
```

**Comment by shubhujf** [comment]
Yeah, I also found out about it later after posting this issue.
I had to install cuda 9.1 and reboot the server then it worked.
Thank You for your reply :)
