### ISSUE TITLE
Cuda out of memory when fp16 training

### ISSUE THREAD

**Issue by kotinigor** [huggingface/transformers#6763]
# ❓ Questions & Help
I have error when run train with fp16

## Details

I want to train Albert model on Russian. I use run_language_modeling.py with some changes in dataset creating. If i run training with fp32 (without --fp flag) and batch_size=2, I will ok. But if i run training with --fp16 flag, i will obtain cuda out of memory error. I tried to decdeare batch size to 1, however, I obtained same error.

**Comment by dhruvrnaik** [comment]
Same issue when running distilbart

**Comment by iliemihai** [comment]
I face the same issue with PEGASUS

**Comment by KylePiira** [comment]
I've run into this with several seq2seq models (Pegasus, BART, T5). Running with fp16 causes increased memory usage.

**Comment by dhruvrnaik** [comment]
I solved my issue by downgrading Pytorch to 1.5.1 and installing Nvidia/Apex.

**Comment by ShirleyHan6** [comment]
Hi @dhruvrnaik , may I ask how much GPU memory is needed for a batch size of 1? Thanks!
