### ISSUE TITLE
RunTime Error: CUDA out of memory when running trainer.train()

### ISSUE THREAD

**Issue by seyonechithrananda** [huggingface/transformers#6979]
## Environment info
- `transformers` version: 3.1.0
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.6.0+cu101 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: P100 GPU instance (Google Colab)
- Using distributed or parallel set-up in script?: No

### Who can help
@sgugger @julien-c @LysandreJik 

## Information

Model I am using (Bert, XLNet ...): RoBERTa with Byte-Pair Encoder (loading from the checkpointed pre-trained model on HuggingFace model hub). 

The problem arises when using:
* [x] the official example scripts: (give details below)
* [x ] my own modified scripts: (give details below)
I modify a variant of the [`01_how_to_train.ipynb`,](https://colab.research.google.com/github/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb) replacing the `LinebyLineTextDataset` as it results in Out of Memory Issues with my text corpus. I built a hugging face NLP dataset which tokenizes the corpus. 

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below): the PubChem 1M SELFIES set, a set of one million SELFIES Strings. "SELFIES" is a 100% chemically valid molecular string representation. You can view the library [here](https://github.com/aspuru-guzik-group/selfies) (I'm one of the developers).

## To reproduce

Reproducing requires a copy of the `shard_00_selfies.txt` dataset (click [here](https://drive.google.com/file/d/1DRq8UgBaKSNfyYtqNMyQ4WimG64sSOFR/view?usp=sharing) for a drive link), as well as the tokenizer's files which can be loaded from the HuggingFace hub with the following name: `seyonec/BPE_SELFIES_PubChem_shard00_50k`

From there, you can just run a variant of the following colab file, with modified file paths of course: https://colab.research.google.com/drive/1a4edCW1b2rSVA_bkqEaywhvGMM_nQzRC?usp=sharing

## Expected behavior

Strangely, the Trainer doesn't output a link to the Weights and Biases run page like it normally did before (using a near-identical script only a couple of days ago). It throws a CUDA out of memory error once I run the `trainer.train()` command:
![Screen Shot 2020-09-06 at 10 42 44 PM](https://user-images.githubusercontent.com/46096704/92343684-621a3e80-f092-11ea-8163-3cff1cd03e6c.png)
<img width="1200" alt="Screen Shot 2020-09-06 at 10 45 58 PM" src="https://user-images.githubusercontent.com/46096704/92343851-d8b73c00-f092-11ea-8c89-a0034191975d.png">

Thanks for the help! Any advice or help is desperately welcome, I've been stuck for the past days with various memory issues with tokenization, and now with running the trainer class for some reason. 😄 

You can check out the main public repository for this project, alongside with the abstract, and more [here](https://github.com/seyonechithrananda/bert-loves-chemistry)!

**Comment by seyonechithrananda** [comment]
For some reason, it works now, but now the Weights and Biases isn't logging the performance. I authorized WandB using `!wanb login` but the runs still aren't logged, strangely.

**Comment by Opdoop** [comment]
Hi @seyonechithrananda , I'm facing the same problem, how did you solve this issue?

**Comment by diegoclarity** [comment]
Ping here about that, I'm having the same problem

**Comment by segef** [comment]
I am suffering from the same problem, would like to know the solution if there is any

**Comment by Lukasz-Cesarski** [comment]
Same problem here. When I run this code on my machine:
https://github.com/huggingface/notebooks/blob/master/examples/token_classification.ipynb
https://colab.research.google.com/drive/1-JIJlao4dI-Ilww_NnTc0rxtp-ymgDgM?usp=sharing

I get:
RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 1.96 GiB total capacity; 785.01 MiB already allocated; 111.25 MiB free; 832.00 MiB reserved in total by PyTorch)

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce MX250       Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   56C    P3    N/A /  N/A |   1897MiB /  2002MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by SourabhG16** [comment]
Hi ,I'm too facing this issue, any solution found on this ?

**Comment by mzeidhassan** [comment]
I am having the same issue and it is recurring. Any solution?
